version: '3.0'

services:

  # NGINX
  # - Reverse proxy to expose services
  #
  nginx:
    build: ./
    container_name: nginx
    networks:
      - elastic-expos
      - elastic-expos-acc
    ports:
      - 80:80
      - 443:443

networks:
  elastic-expos:
     external: true
  elastic-expos-acc:
     external: true
           