version: '3.0'

services:

  # NGINX
  # - Reverse proxy to expose services
  #
  nginx:
    build: ./
    container_name: nginx
    restart: always
    networks:
      - elastic-expos
      - elastic-expos-acc
    volumes:
      - /var/log/nginx/:/var/log/nginx  
    ports:
      - 443:443
    expose:
      - 80  
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3  
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 15m  

networks:
  elastic-expos:
     external: true
  elastic-expos-acc:
     external: true
           