version: '3.8'

services:
    reverse-proxy:
        image: caddy/caddy:2-alpine
        container_name: reverse-proxy
        restart: unless-stopped
        networks:
          - elastic-expos
        ports:
            - "80:80"
            - "443:443"
        volumes:
        - caddy_data:/data
        - caddy_config:/config
        - $PWD/Caddyfile:/etc/caddy/Caddyfile
        - $PWD/certs:/data/certs

networks:
  elastic-expos:
     external: true

volumes:
  caddy_data:
  caddy_config:
